config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  get 'recipes/show'
  devise_for :users
  root to: "public_recipes#index"

  resources :users do
    resources :foods
    resources :recipes, only: [:index, :show, :destroy] do 
      resources :recipe_foods 
      resources :shopping_list
    end
  end

  resources :public_recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # associations
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  # validations
  validates :name, presence: true, length: { minimum: 2 }
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :description, presence: true, length: { minimum: 3 }

  def total_price
    foods.sum('price  * recipe_foods.quantity')
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[index show destroy]
  load_and_authorize_resource

  before_action :recipe_id, only: %i[show destroy]
  before_action :user_id, only: %i[index destroy]
  before_action :recipe_obj, only: %i[show]
  before_action :user_obj, only: %i[show]

  def index
    @recipes = Recipe.where(user_id: @user_id).order(id: :desc)
  end

  def show
    @recipe_foods = @recipe.recipe_foods.includes(:recipe, :food)
  end

  def destroy
    recipe = Recipe.find(@recipe_id)
    if recipe.destroy
      flash[:notice] = 'Recipe removed successfully!'
    else
      flash.now[:alert] = 'Recipe could not be removed'
    end
    redirect_to user_recipes_path(@user_id)
  end

  private

  def recipe_id
    @recipe_id = params[:id]
  end

  def user_id
    @user_id = params[:user_id]
  end

  def recipe_obj
    @recipe = Recipe.find(params[:id])
  end

  def user_obj
    @user = User.find(params[:user_id])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<section id='recipes'>
  <div class='py-5'>
    <table class="table table-bordered table-hover bs">
      <thead class='bg-light'>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% if @recipes.empty? %>
          <tr>
            <td rowspan='4'><i>No recipes</i></td>
          </tr>
        <% else %>
          <% @recipes.each_with_index do |recipe, i| %>
            <tr>
              <th scope="row"><%= 1 + i %></th>
              <td><%= recipe.name %></td>
              <td><%= recipe.description %></td>
              <td class='d-flex justify-content-start gap-2'>
                <% if can? :read, recipe %>
                  <%= link_to 'View', user_recipe_path(recipe.user_id, recipe.id), class: "btn btn-outline-info btn-sm" %>
                <% end %>
                
                <% if can? :destroy, recipe %>
                  <%= button_to "Remove", user_recipe_path(recipe.user_id, recipe.id), method: :delete, class: "btn btn-outline-danger btn-sm" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/recipes/show.html.erb
<section id='recipe-details'>
  <div class='my-5'>
    <h1 class='text-center underline'><%= @recipe.name %></h1>
    <hr>
    <div class='row'>
      <div class='col-sm-6'>
        <table class='table table-bordered table-sm'>
          <tr>
            <th scope="row">Preparation time</th>
            <td scope="col"><%= @recipe.preparation_time.to_s + ' min' %></td>
          </tr>
          <tr>
            <th scope="row">Cooking time</th>
            <td scope="col"><%= @recipe.cooking_time.to_s + ' min' %></td>
          </tr>
        </table>
      </div>
      <div class='col-sm-6'>
        <div class='d-flex justify-content-end'>
          <div class="form-group mt-3">
            <div class="form-check form-check-inline">
              <input type="checkbox" class="form-check-input" id="public" 
              <% if @recipe.public %>
              checked="checked" 
              <% end %>
              />
              <label class="form-check-label" for="public">Public</label>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class='my-3 d-flex justify-content-between'>
        <% if can? :read, @recipe %>
        <%= link_to user_recipe_shopping_list_index_path(@user, @recipe) do %>
          <button class='btn btn-outline-info btn-sm'>Generate shopping list</button>
          <%end%>
        <% end %>

        <% if can? :read, @recipe %>
          <%= link_to 'Add ingredient', new_user_recipe_recipe_food_path(@recipe.user_id, @recipe.id), class: 'btn btn-outline-info btn-sm' %>
        <% end %>
    </div>

    <hr>

    <table class="table table-hover table-bordered table-sm bs">
      <thead class='bg-light'>
        <tr>
          <th>#</th>
          <th>Food</th>
          <th>Quantity</th>
          <th>Price Per Quantity</th>
          <th>Value</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% if @recipe.foods.empty? %>
          <tr>
            <th colspan='5'>
               <i>No food or ingredients added</i>
            </th>
          </tr>
        <% else %>
          <% @recipe_foods.each_with_index do |rf, i| %>
            <tr>
              <th scope="row"><%= i + 1 %></th>
              <td><%= rf.food.name %></td>
              <td><%= rf.quantity %></td>
              <td><%= '$'+ rf.food.price.to_s %></td>
              <td><%= '$'+(rf.food.price * rf.quantity).to_s %></td>
              <td class='d-flex gap-2'>
                <% if can? :update, rf.recipe %>
                  <%= link_to 'Modify', edit_user_recipe_recipe_food_path(@recipe.user_id, @recipe.id, rf.id), class:'btn btn-outline-info btn-sm' %>
                <% end %>

                <% if can? :destroy, rf.recipe %>
                  <%= button_to "Remove", user_recipe_recipe_food_path(@recipe.user_id, @recipe.id, rf.id), method: :delete, class: "btn btn-outline-danger btn-sm" %>
                <% else %>
                  <i>N/A</i>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</section>