config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  get 'recipes/show'
  devise_for :users
  root to: "public_recipes#index"

  resources :users do
    resources :foods
    resources :recipes, only: [:index, :show, :destroy] do 
      resources :recipe_foods 
      resources :shopping_list
    end
  end

  resources :public_recipes
end

app/models/food.rb
class Food < ApplicationRecord
  # Validations
  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :user_id, presence: true

  # associations
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, dependent: :destroy
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # before_action :set_food, only: %i[show destroy]
  # before_action :set_user, only: %i[index show create]

  # find all food for a users
  def index
    @foods = Food.all.order(created_at: :desc)
  end

  def destroy
    food = Food.find(params[:id])

    if food.destroy
      flash[:notice] = 'Food removed successfully!'

    else
      flash.now[:alert] = 'Food could not be removed'
    end
    redirect_to user_foods_url
  end

  def new
    @new_food = Food.new
  end

  def create
    @food = Food.new(food_params)

    respond_to do |format|
      format.html do
        if @food.save!
          redirect_to user_foods_url
        else
          redirect_to new_user_food_path(current_user)
        end
      end
    end
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity).merge(user_id: current_user.id)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<section class="container">
    <div class="container my-5 d-flex justify-content-end">
    <%= link_to 'Add food', new_user_food_path, 'data-ripple-light': true,  class: "btn btn-outline-primary btn-sm" %>
    </div>
    <div class="mt-5 mx-5">
    <table class="table table-bordered table-hover bs mx-5">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Measurement unit</th>
        <th scope="col">Unit price in $</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
   
    <tbody>
    <% if @foods.empty? %>
    <tr>
        <td rowspan='4'><i>No Foods</i></td>
    </tr>
    <% else %>
    <% @foods.each do|food| %> 
      <tr>
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td> <%= food.price %> </td>
        <td> <%= button_to 'Delete', user_food_path(food.user_id, food.id), method: :delete, 'data-ripple-light': true,  class: "btn btn-outline-danger btn-sm" %></td>
      </tr>
      <%end%>
    <%end%>  
    </tbody>
        </table>
    </div>
</section>

app/views/foods/new.html.erb
<section class="container d-flex justify-content-center">
<div class="container p-5 d-flex  flex-column w-50">
 <h1 class="text-center mb-3"> Add new food </h1>
 <div class="border border-3 p-3 ">
 <%= form_with model:@new_food, url: user_foods_path do |form| %>
    <div class="mb-3  d-flex flex-column ">
    <label class ="form-label">Food name</label>
    <%= form.text_field :name %>
    </div>

    
    <div class="mb-3  d-flex flex-column ">
    <label class="form-label"> Measurement_unit</label>
    <%= form.text_field :measurement_unit %>
    </div>

    <div class="mb-3  d-flex flex-column">
    <label class="form-label">Price</label>
    <%= form.text_field :price %>
    </div>

    <div class="mb-3  d-flex flex-column">
    <label class="form-label w">Quantity</label>
    <%= form.text_field :quantity %>
    </div>
    <div>
    <%= form.submit 'Create Food', class: 'btn btn-gradient btn-primary block' %>
    </div>

    <%end%>
 </div>
 
</div>
</section>