config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  get 'recipes/show'
  devise_for :users
  root to: "public_recipes#index"

  resources :users do
    resources :foods
    resources :recipes, only: [:index, :show, :destroy] do 
      resources :recipe_foods 
      resources :shopping_list
    end
  end

  resources :public_recipes
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  # validation
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :food, uniqueness: { scope: :recipe, message: 'already exists in this recipe' }

  # associations
  belongs_to :food
  belongs_to :recipe
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create destroy]
  before_action :recipe_obj, only: %i[new create edit update destroy]
  before_action :user_obj, only: %i[new destroy]
  before_action :food_list, only: %i[new create edit update]

  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe_food = RecipeFood.new(recipe_foods_params)

    begin
      @recipe_food.save!
      flash[:notice] = 'Food added successfully'
      redirect_to "/users/#{params[:user_id]}/recipes/#{params[:recipe_id]}"
    rescue ActiveRecord::RecordInvalid => e
      flash[:alert] = e.message
      redirect_to "/users/#{params[:user_id]}/recipes/#{params[:recipe_id]}/recipe_foods/new"
    end
  end

  def edit
    @edit_recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])

    begin
      @recipe_food.update!(recipe_foods_params)
      flash[:notice] = 'Food updated successfully'
      redirect_to "/users/#{params[:user_id]}/recipes/#{params[:recipe_id]}"
    rescue ActiveRecord::RecordInvalid => e
      flash[:alert] = e.message
      redirect_to "/users/#{params[:user_id]}/recipes/#{params[:recipe_id]}/recipe_foods/#{params[:id]}/edit"
    end
  end

  def destroy
    recipe_food = RecipeFood.find(params[:id])

    if recipe_food.destroy
      flash[:success] = 'Recipe food item was successfully deleted.'
    else
      flash.now[:error] = 'There was a problem deleting the recipe food item.'
    end
    redirect_to user_recipe_path(user_obj, recipe_obj)
  end

  private

  def recipe_foods_params
    params.require(:recipe_food).permit(:food_id, :quantity).merge(recipe_id: params[:recipe_id])
  end

  def recipe_obj
    @recipe = Recipe.find(params[:recipe_id])
  end

  def user_obj
    @user = User.find(params[:user_id])
  end

  def food_list
    @foods = Food.select(:id, :name)
  end
end

app/views/recipe_foods/edit.html.erb
<section class="bs-section">
  <div class="my-5">
    <%= form_with model: @edit_recipe_food, method: 'PUT', url: user_recipe_recipe_food_path do |form| %>
      <div class='d-flex justify-content-center align-items-center gap-2'>
        <svg class='svg-icon pb-2 text-warning' fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"></path>
        </svg>
        <h2 class='text-warning'>Edit Ingredient</h2>
      </div>
      
      <hr>

      <div class="field mb-3">
        <%= form.label "Food", class: "form-label" %><br>
        <%= form.select :food_id, options_for_select(@foods.collect { |f| [f.name, f.id] }, selected: @edit_recipe_food.food_id), {prompt: "Select food", required: true, class: "form-select"} %>
      </div>

      <div class="field mb-3">
        <%= form.label :quantity, class: "form-label" %><br>
        <%= form.number_field :quantity, value: @edit_recipe_food.quantity, min: 0, step: 1, required: true, class: "form-control" %>
      </div>

      <div class="actions d-grid mb-3">
        <%= form.submit "Submit", class: "btn btn-outline-warning" %>
      </div>

      <%= link_to "Go back", user_recipe_path(@recipe.user_id, @recipe.id), class: "text-center" %>
    <% end %>
  </div>
</section>

app/views/recipe_foods/new.html.erb
<section class='bs-section'>
  <div class='my-5'>
    <%= form_with model: @recipe_food, url: user_recipe_recipe_foods_path do |form| %>
      <div class='d-flex justify-content-center align-items-center gap-2'>
        <svg class='svg-icon pb-2 text-primary' fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"></path>
        </svg>
        <h2 class='text-primary'>Add ingredient</h2>
      </div>

      <hr>

      <div class='field mb-3'>
        <%= form.label 'Food', class: 'form-label' %><br>
        <%= form.select :food_id, options_for_select(@foods.collect { |f| [f.name, f.id] }), {prompt: "Select food", required: true, class: 'form-select'} %>
      </div>

      <div class='field mb-3'>
        <%= form.label :quantity, class: 'form-label' %><br>
        <%= form.number_field :quantity, min: 0, step: 1, required: true, class: 'form-control' %>
      </div>

      <div class='actions d-grid mb-3'>
        <%= form.submit 'Submit', class: 'btn btn-outline-primary' %>
      </div>

      <%= link_to 'Go back', user_recipe_path(@recipe.user_id, @recipe.id), class:'text-center' %>
    <% end %>
  </div>
</section>